version: "2"
sql:
  - engine: "mysql"
    queries: "../internal/database/mysql/query.sql"
    schema: "../internal/database/mysql/migrations/1_create_tables.up.sql"
    gen:
      go:
        package: "sqlc"
        out: "../internal/database/mysql/"
        emit_json_tags: true
